apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps-echo
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: core-ingress-nginx
  sourceRef:
    kind: GitRepository
    name: kubernetes
  path: ./k8s/apps/demo/echo
  prune: true
