
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      chart: grafana
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: ">=6.29.2"
  interval: 5m
  values:
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - disableDeletion: false
          editable: false
          folder: flux
          name: flux
          options:
            path: /var/lib/grafana/dashboards/flux
          orgId: 1
          type: file
        - disableDeletion: false
          editable: false
          folder: grafana / Mimir
          name: grafana-mimir
          options:
            path: /var/lib/grafana/dashboards/grafana-mimir
          orgId: 1
          type: file
        - disableDeletion: false
          editable: false
          folder: grafana / Loki
          name: grafana-loki
          options:
            path: /var/lib/grafana/dashboards/grafana-loki
          orgId: 1
          type: file
    dashboards:
      flux:
        cluster:
          datasource: Mimir
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/cluster.json
        control-plane:
          datasource: Mimir
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/control-plane.json
        logs:
          datasource: Loki
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/logs.json
      grafana-loki:
        chunks:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/loki/main/production/loki-mixin-compiled/dashboards/loki-chunks.json
        deletion:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/loki/main/production/loki-mixin-compiled/dashboards/loki-deletion.json
        logs:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/loki/main/production/loki-mixin-compiled/dashboards/loki-logs.json
        operational:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/loki/main/production/loki-mixin-compiled/dashboards/loki-operational.json
        reads:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/loki/main/production/loki-mixin-compiled/dashboards/loki-reads.json
        reads-resources:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/loki/main/production/loki-mixin-compiled/dashboards/loki-reads-resources.json
        recording-rules:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/loki/main/production/loki-mixin-compiled/dashboards/loki-mixin-recording-rules.json
        retention:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/loki/main/production/loki-mixin-compiled/dashboards/loki-retention.json
        writes:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/loki/main/production/loki-mixin-compiled/dashboards/loki-writes.json
        writes-resources:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/loki/main/production/loki-mixin-compiled/dashboards/loki-writes-resources.json
      grafana-mimir:
        alertmanager:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
        alertmanager-resources:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json
        compactor:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-compactor.json
        compactor-resources:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json
        config:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-config.json
        object-store:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-object-store.json
        overrides:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-overrides.json
        overview:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-overview.json
        overview-networking:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-overview-networking.json
        overview-resources:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-overview-resources.json
        queries:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-queries.json
        reads:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-reads.json
        reads-networking:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json
        reads-resources:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json
        remote-ruler-reads:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
        remote-ruler-reads-resources:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads-resources.json
        rollout-progress:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json
        ruler:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
        scaling:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-scaling.json
        slow-queries:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json
        tenants:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
        top-tenants:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json
        writes:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-writes.json
        writes-networking:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json
        writes-resources:
          datasource: Mimir
          url: https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - isDefault: true
          jsonData:
            timeInterval: 15s
          name: Mimir
          type: prometheus
          uid: mimir
          url: http://grafana-mimir-nginx.grafana-mimir.svc.cluster.local/prometheus/
        - isDefault: false
          name: Loki
          type: loki
          uid: loki
          url: http://loki-gateway.grafana-loki.svc.cluster.local/
        - isDefault: false
          jsonData:
            nodeGraph:
              enabled: true
          name: Tempo
          type: tempo
          uid: tempo
          url: http://grafana-tempo-query-frontend.grafana-tempo.svc.cluster.local:3100
        - name: Phlare
          type: phlare
          uid: phlare
          url: http://grafana-phlare-querier.grafana-phlare.svc.cluster.local:4100/
    env:
      GF_DIAGNOSTICS_PROFILING_ADDR: 0.0.0.0
      GF_DIAGNOSTICS_PROFILING_ENBLED: true
      GF_DIAGNOSTICS_PROFILING_PORT: 6060
      GF_FEATURE_TOGGLES_ENABLE: flameGraph
    grafana.ini:
      server:
        root_url: https://grafana.example.com
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        ingress.kubernetes.io/ssl-redirect: "true"
      enabled: true
      hosts:
      - grafana.example.com
      ingressClassName: haproxy
      tls:
      - hosts:
        - grafana.example.com
        secretName: grafana.example.com
    podAnnotations:
      phlare.grafana.com/port: "6060"
      phlare.grafana.com/scrape: "true"
    rbac:
      pspEnabled: false
      pspUSeAppArmor: false
    sidecar:
      alerts:
        enabled: true
        ignoreAlreadyProcessed: true
        label: grafana-alert
        resource: both
        searchNamespace: ALL
      dashboards:
        enabled: true
        folder: /tmp/dashboards
        folderAnnotation: grafana-dashboard-folder
        label: grafana-dashboard
        labelValue: null
        provider:
          allowUiUpdates: false
          disableDelete: false
          foldersFromFilesStructure: true
          name: sidecarProvider
          orgid: 1
        searchNamespace: ALL
        watchMethod: WATCH
      enableUniqueFilenames: false
      plugins:
        enabled: true
        label: grafana-plugin
        labelValue: null
        resource: both
        searchNamespace: null
        watchMethod: WATCH
