---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          ports:
            - containerPort: 3100
          args:
            - --log.level=info
            - --backend=loki
            - --backend.max-retries=10
            - --backend.url=http://grafana-loki:3100/loki/api/v1/push
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  ports:
    - name: http
      port: 3100
  selector:
    app: tempo
