apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-loki
  template:
    metadata:
      labels:
        app: grafana-loki
    spec:
      containers:
        - name: grafana-loki
          image: grafana/loki:latest
          ports:
            - containerPort: 3100
          args:
            - -config.file=/etc/loki/local-config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/loki
      volumes:
        - name: config
          configMap:
            name: grafana-loki-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-loki
spec:
  ports:
    - name: http
      port: 3100
  selector:
    app: grafana-loki

