
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-tempo
spec:
  chart:
    spec:
      chart: tempo-distributed
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: ">=1.2.2"
  interval: 15m
  values:
    compactor:
      config:
        compaction:
          block_retention: 12h
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 2Gi
    distributor:
      autoscaling:
        enabled: false
      config:
        log_received_spans:
          enabled: true
          filter_by_status_error: true
          include_all_attributes: true
      replicas: 1
    global:
    global_overrides:
      max_bytes_per_tag_values_query: 0
      metrics_generator_processors:
      - service-graphs
      - span-metrics
    ingester:
      autoscaling:
        enabled: false
      replicas: 2
    metaMonitoring:
      grafanaAgent:
        enabled: false
      serviceMonitor:
        enabled: true
        labels:
          instance: primary
    metricsGenerator:
      config:
        storage:
          remote_write:
          - url: http://grafana-mimir-nginx.grafana-mimir.svc.cluster.local/api/v1/push
      enabled: true
    minio:
      enabled: false
    search:
      enabled: true
    serviceAccount:
      name: grafana-tempo
    storage:
      trace:
        backend: local
    tempo:
      structuredConfig:
        query_frontend:
          search:
            max_duration: 12h0m0s
        storage:
          trace:
            block:
              version: vParquet
            pool:
              max_workers: 100
              queue_depth: 10000
    traces:
      otlp:
        grpc:
          enabled: true
