apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: kustomize
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
  - kind: Kustomization
    name: '*'
