apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-loki-config
data:
  local-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
configMapGenerator:
- name: grafana-loki-config
  files:
  - config/grafana-loki-config.yaml
  namespace: flux-system

