apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  replicas: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  ruleSelector:
    matchLabels:
      role: prometheus
  alerting:
    alertmanagers:
    - namespace: prometheus
      name: alertmanager-main
      port: web
  resources:
    requests:
      memory: 400Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
  serviceAccountName: prometheus
  podMonitorNamespaceSelector:
    matchLabels:
      prometheus: kube-prometheus-stack
  podMonitorSelector:
    matchLabels:
      role: prometheus
  retention: 24h
  serviceMonitorSelector:
    matchLabels:
      role: prometheus
  version: v2.33.0