apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: config-core
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: kubernetes
  path: ./k8s/clusters/demo/core
  prune: true
  validation: client
